name: fabrica-fice

services:
  db:
    container_name: fabrica-fice-prod-db
    image: pgvector/pgvector:pg16
    env_file: .env
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    # ports:
    #   - "5432:5432"
    volumes:
      - fabrica-fice_prod_db:/var/lib/postgresql/data
    networks:
      - fabrica-network
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: 512M
        reservations:
          cpus: "0.10"
          memory: 256M
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 3

  web:
    container_name: fabrica-fice-prod-web
    build:
      context: .
      target: prod
      args:
        APP_VERSION: ${APP_VERSION:-latest}
        APP_ENV: production
    image: fabrica-fice:${APP_VERSION}
    pull_policy: build
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    environment:
      - APP_ENV=production
      - APP_VERSION=${APP_VERSION:-latest}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    labels:
      - org.opencontainers.image.version=${APP_VERSION:-latest}
    networks:
      - fabrica-network
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: 512M
        reservations:
          cpus: "0.10"
          memory: 128M

volumes:
  fabrica-fice_prod_db:

networks:
  fabrica-network:
    external: true
  # fabrica-network:
  #   driver: bridge
