name: fabrica-fice

services:
  fabrica-fice-db:
    container_name: fabrica-fice-prod-db
    image: pgvector/pgvector:pg17
    env_file: .env
    environment:
      - PGDATA=/var/lib/postgresql/fice-data
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
    # ports:
    #   - "5432:5432"
    volumes:
      - fabrica-fice-data:/var/lib/postgresql/fice-data
    networks:
      - fabrica-network
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: 512M
        reservations:
          cpus: "0.10"
          memory: 256M
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 3

  fabrica-fice-web:
    container_name: fabrica-fice-prod-web
    build:
      context: .
      target: prod
      args:
        APP_VERSION: ${APP_VERSION:-latest}
        APP_ENV: production
    image: fabrica-fice:${APP_VERSION}
    pull_policy: build
    # ports:
    #   - "3003:3000"
    depends_on:
      fabrica-fice-db:
        condition: service_healthy
    env_file: .env
    environment:
      - APP_ENV=production
      - APP_VERSION=${APP_VERSION:-latest}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    labels:
      - org.opencontainers.image.version=${APP_VERSION:-latest}
    networks:
      - fabrica-network
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: 512M
        reservations:
          cpus: "0.10"
          memory: 128M

volumes:
  fabrica-fice-data:

networks:
  fabrica-network:
    external: true
